### ISSUE TITLE
BUG: Delete .idea folder and add .idea gitignore  🤣

### ISSUE THREAD

**Issue by nijat** [Mansurlzd/shopping-cart-frontend#2]

**Comment by nijat** [comment]
It would be better if you give access to users who wants to contribute to the important project. I tried to create PR, but it requires admin access.

**Comment by Mansurlzd** [comment]
Hello Nijat, thanks for noticing, we will definitely fix this critical bug in the upcoming PR. Unfortunately, I  can't give you admin access. Have a nice day :)
